version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello from my-multi-repo"

  trigger-new-pipeline:
      docker: 
        - image: cimg/base:2021.11
      resource_class: small
      steps:
        - run:
            name: Ping another pipeline
            command: |
              curl --request POST \
                --url https://circleci.com/api/v2/project/gh/jenny-miggin/service-a/pipeline \
                --header "Circle-Token: $CIRCLE_API_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch":"main"}'

workflows:
  run-jobs:
    jobs:
      - build
      - trigger-new-pipeline:
          requires:
            - build
          context:
            - cci